# -*- coding: utf-8 -*-
"""Excel Even Numbered Raw Hider.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwqHH53yl-KZ7zqDbjfRJ9_KrRlSBz9N
"""

from openpyxl import load_workbook

# Load the workbook and select the sheet
file_path = "Generation data 1.xlsx"  # Replace with your file path
workbook = load_workbook(file_path)
sheet = workbook.active  # Use the active sheet or specify a sheet name like workbook['Sheet1']

# Loop through rows and hide even-numbered rows
for row in range(2, sheet.max_row + 1, 2):  # Start from row 2 (first even row)
    sheet.row_dimensions[row].hidden = True

# Save the updated workbook
workbook.save("updated_" + file_path)
print("Even-numbered rows have been hidden successfully!")